<?php

declare(strict_types=1);

namespace App\Service;

use InvalidArgumentException;

/**
 * Derives the payment brand CSS tokens from one base colour per brand.
 *
 * {@see PaymentBrand::BRANDS} carries a single published colour per method,
 * which is the only brand fact that has to be stored. The other four tokens
 * (`soft`, `line`, `ink`, `on`) are the same hue at a different lightness, and
 * they existed only as twelve more hand-written hex values per table in
 * resources/css/app.css. That is the drift this class removes: a recolour meant
 * `PaymentBrand::BRANDS` was updated and nobody compared it against the button
 * next to it, so the stylesheet quietly kept the old pink. Worse, the two
 * tables could disagree with *each other* — a dark `--pay-soft` tuned for
 * rocket would still be shipped against bKash, where it reads as a grey block.
 *
 * So the colours are computed, not stored, from two rules:
 *
 *   - hue and saturation come from the brand colour, so a brand stays
 *     recognisable however far the lightness moves;
 *   - lightness comes from a fixed target per token, so a brand that is already
 *     dark (Rocket's #8B3392) and one that is already light (Nagad's #EE1C25)
 *     still land in the same place in the UI.
 *
 * Every value is chosen for contrast rather than by eye, which is the part a
 * hand-written table gets wrong when a new brand is added at 6pm:
 * `--pay-ink` on `--pay-soft` is guaranteed readable, and `--pay-on` falls back
 * off white only when white would actually be unreadable on the fill.
 *
 * The rendered block is written into resources/css/app.css by
 * `php scripts/generate-pay-palette.php`, which runs as part of `npm run build`.
 * PaymentBrandPaletteTest asserts the committed file still matches, so a
 * changed brand colour cannot be merged without its CSS following.
 *
 * This is presentation, not policy: it deliberately holds no state and reaches
 * for no repository, so the build script can call it without booting the app.
 */
final class PaymentBrandPalette
{
    /** The tokens a `.pay-*` rule must define, in the order they are written. */
    public const TOKENS = ['--pay', '--pay-soft', '--pay-line', '--pay-ink', '--pay-on'];

    /**
     * First line of the generated region. The script rewrites everything up to
     * and including {@see MARKER_END}, so anything hand-written belongs outside.
     */
    public const MARKER_BEGIN = '/* >>> generated by scripts/generate-pay-palette.php — do not edit >>> */';

    public const MARKER_END = '/* <<< generated — rerun `php scripts/generate-pay-palette.php` <<< */';

    // ─── light mode targets ─────────────────────────────────────────────

    /**
     * `--pay-soft` is the fill behind a selected card and behind the amount
     * panel: pale enough to sit under body text, saturated enough that the hue
     * still reads. 94% lightness is the practical floor — much lower and a
     * saturated hue stops looking like a tint and starts looking like a
     * highlight, which is not what "this card is selected" should look like.
     */
    private const SOFT_LIGHTNESS = 0.94;
    private const SOFT_SATURATION = 0.62;

    /**
     * `--pay-line` is the border around that fill. One step darker than `soft`
     * is the whole point of the token: a border that is invisible is what made
     * the selected card look unselected.
     */
    private const LINE_LIGHTNESS = 0.84;
    private const LINE_SATURATION = 0.80;

    /**
     * `--pay-ink` is the text drawn on `soft` — the amount, the eyebrow, the
     * card label. Lightness is derived from the brand's own (so a dark brand
     * gets a proportionally darker ink) and then clamped: unclamped, a light
     * brand such as Nagad's #EE1C25 would produce an unreadable pink label.
     */
    private const INK_LIGHTNESS_DROP = 0.22;
    private const INK_LIGHTNESS_MIN = 0.18;
    private const INK_LIGHTNESS_MAX = 0.38;
    private const INK_SATURATION = 0.95;

    // ─── dark mode targets ──────────────────────────────────────────────

    /**
     * A light card needs the opposite treatment, and the same five numbers
     * cannot do both jobs:
     *
     *   --pay      the 500/600 brand shade is too dark to read as a label on a
     *              dark card, so it is lifted until it is a tint of itself
     *   --pay-soft a near-white fill would be a glowing block, so the brand
     *              shade is pushed down towards black instead
     *   --pay-line a border you can see without it glaring
     *   --pay-ink  a near-white with a trace of the hue, not the saturated
     *              light tint, which vibrates against a dark fill
     *   --pay-on   dark, because the solid button is now a light block
     */
    private const DARK_PAY_LIGHTNESS_DROP = 0.22;
    private const DARK_PAY_LIGHTNESS_MIN = 0.62;
    private const DARK_PAY_LIGHTNESS_MAX = 0.80;
    private const DARK_PAY_SATURATION = 0.95;

    private const DARK_SOFT_LIGHTNESS_RATIO = 0.28;
    private const DARK_SOFT_SATURATION = 0.77;

    private const DARK_LINE_LIGHTNESS_RATIO = 0.70;
    private const DARK_LINE_SATURATION = 0.80;

    private const DARK_INK_LIGHTNESS_LIFT = 0.40;
    private const DARK_INK_LIGHTNESS_MAX = 0.95;
    private const DARK_INK_SATURATION = 0.15;

    // ─── the text drawn on a solid brand fill ───────────────────────────

    /**
     * White is the right answer for almost every brand button, and it is what
     * bKash, Nagad and Rocket all publish, so the fallback has to be rare.
     *
     * The threshold is a comparison, not a constant: of the two candidates,
     * white and a dark tint of the same hue, the more readable one wins. White
     * takes every light-mode brand that all three operators publish, so nothing
     * on-brand is lost; a dark label appears exactly when white would be the
     * weaker of the two, which is always the case in dark mode, where `--pay`
     * is a lifted tint that no white text can sit on.
     *
     * 4.5:1 is not the target. `.pay-accent-bg` is a `text-sm font-semibold`
     * button, so AA is 4.5:1 — and Nagad's published red reaches 4.35:1 against
     * white and only 2.9:1 against the dark tint, so asking for 4.5 here would
     * mean recolouring the brand, which is the one thing this class must not
     * do. PaymentBrandPaletteTest pins the floor this rule actually delivers.
     */
    private const WHITE = '#ffffff';
    private const ON_SATURATION = 0.85;
    private const ON_LIGHTNESS_RATIO = 0.35;
    private const ON_LIGHTNESS_MIN = 0.10;
    private const ON_LIGHTNESS_MAX = 0.22;

    /**
     * Light-mode tokens for one brand colour.
     *
     * `--pay` is passed through verbatim rather than round-tripped through
     * HSL: the brand table is the source of truth, and re-encoding a hex colour
     * that is already canonical would only give it a chance to change.
     *
     * @return array<string, string> token => `#rrggbb`
     */
    public function lightTokens(string $color): array
    {
        [$h, $s, $l] = self::toHsl($color);

        return [
            '--pay' => self::lowerHex($color),
            '--pay-soft' => self::hslToHex($h, $s * self::SOFT_SATURATION, self::SOFT_LIGHTNESS),
            '--pay-line' => self::hslToHex($h, $s * self::LINE_SATURATION, self::LINE_LIGHTNESS),
            '--pay-ink' => self::hslToHex(
                $h,
                min($s * self::INK_SATURATION, 1.0),
                self::clamp($l - self::INK_LIGHTNESS_DROP, self::INK_LIGHTNESS_MIN, self::INK_LIGHTNESS_MAX)
            ),
            '--pay-on' => self::onColour($h, $s, $l, $color),
        ];
    }

    /**
     * Dark-mode tokens for one brand colour. Derived from the *brand* hue, not
     * from the light `--pay`, so the two tables cannot describe two different
     * colours.
     *
     * @return array<string, string> token => `#rrggbb`
     */
    public function darkTokens(string $color): array
    {
        [$h, $s, $l] = self::toHsl($color);

        $pay = self::hslToHex(
            $h,
            $s * self::DARK_PAY_SATURATION,
            self::clamp($l + self::DARK_PAY_LIGHTNESS_DROP, self::DARK_PAY_LIGHTNESS_MIN, self::DARK_PAY_LIGHTNESS_MAX)
        );

        return [
            '--pay' => $pay,
            '--pay-soft' => self::hslToHex(
                $h,
                $s * self::DARK_SOFT_SATURATION,
                max(self::clamp($l * self::DARK_SOFT_LIGHTNESS_RATIO, 0.0, 0.45), 0.08)
            ),
            '--pay-line' => self::hslToHex(
                $h,
                $s * self::DARK_LINE_SATURATION,
                self::clamp($l * self::DARK_LINE_LIGHTNESS_RATIO, 0.0, 0.45)
            ),
            '--pay-ink' => self::hslToHex(
                $h,
                $s * self::DARK_INK_SATURATION,
                self::clamp($l + self::DARK_INK_LIGHTNESS_LIFT, 0.0, self::DARK_INK_LIGHTNESS_MAX)
            ),
            // Measured against the lifted `--pay`, which is the block the text
            // is actually drawn on: white will never clear the threshold here,
            // so every dark brand resolves to the dark end of its own hue.
            '--pay-on' => self::onColour($h, $s, $l, $pay),
        ];
    }

    /**
     * The whole generated block, markers included.
     *
     * Kept as one string rather than spliced together by the script so that
     * `--check` and the unit test compare the *same* value the build writes:
     * a generator whose output is assembled in two places is a generator with
     * two chances to disagree with itself.
     */
    public function generatedRegion(): string
    {
        $brands = PaymentBrand::BRANDS;

        $light = [];
        foreach ($brands as $key => $brand) {
            $light[] = self::rule('.pay-' . $key, $brand['color'], light: true);
        }

        $dark = [];
        foreach ($brands as $key => $brand) {
            $dark[] = self::rule('.dark .pay-' . $key, $brand['color'], light: false);
        }

        // The unbranded fallback is derived from the same constant `get()` hands
        // the template, so an unknown method cannot render in one green here and
        // a different green there.
        $fallback = PaymentBrand::FALLBACK_COLOR;
        $light[] = "\n" . self::fallbackNote();
        $light[] = self::rule('.pay-default', $fallback, light: true);
        $dark[] = self::rule('.dark .pay-default', $fallback, light: false);

        return implode("\n", [
            self::MARKER_BEGIN,
            '/* Light. `--pay` is the brand colour from PaymentBrand::BRANDS; the',
            '   other four are this class\'s fixed tints of its hue. */',
            implode("\n", $light),
            '',
            '/* Dark, same hues re-lit for a dark card: see the header note. */',
            implode("\n", $dark),
            self::MARKER_END,
        ]) . "\n";
    }

    // ─── contrast, for the test and for anyone adding a brand ───────────

    /**
     * WCAG 2.x contrast ratio between two colours, 1.0–21.0.
     *
     * Public because the interesting failures here are invisible: a generated
     * palette is only worth generating if the guarantee is checkable, and the
     * check is a number, not an opinion.
     */
    public static function contrastRatio(string $a, string $b): float
    {
        $la = self::luminance($a);
        $lb = self::luminance($b);

        return (max($la, $lb) + 0.05) / (min($la, $lb) + 0.05);
    }

    // ─── internals ──────────────────────────────────────────────────────

    private function rule(string $selector, string $color, bool $light): string
    {
        $tokens = $light ? $this->lightTokens($color) : $this->darkTokens($color);

        $declarations = [];
        foreach (self::TOKENS as $token) {
            $declarations[] = $token . ': ' . $tokens[$token];
        }

        return $selector . ' { ' . implode('; ', $declarations) . '; }';
    }

    private static function fallbackNote(): string
    {
        return implode("\n", [
            '/* An unbranded fallback, so `cssClass()` can hand the template a class name',
            '   for a method it does not know and the card still renders in the site',
            '   primary rather than with every `var(--pay)` resolving to nothing. */',
        ]);
    }

    private static function onColour(float $h, float $s, float $l, string $against): string
    {
        $dark = self::hslToHex(
            $h,
            $s * self::ON_SATURATION,
            self::clamp($l * self::ON_LIGHTNESS_RATIO, self::ON_LIGHTNESS_MIN, self::ON_LIGHTNESS_MAX)
        );

        return self::contrastRatio(self::WHITE, $against) >= self::contrastRatio($dark, $against)
            ? self::WHITE
            : $dark;
    }

    private static function luminance(string $color): float
    {
        [$r, $g, $b] = self::toRgb($color);

        $channel = static fn(float $c): float => $c <= 0.03928
            ? $c / 12.92
            : (($c + 0.055) / 1.055) ** 2.4;

        return 0.2126 * $channel($r) + 0.7152 * $channel($g) + 0.0722 * $channel($b);
    }

    /**
     * @return array{float, float, float} hue in degrees [0, 360), saturation and
     *                                  lightness in [0, 1]
     */
    private static function toHsl(string $color): array
    {
        [$r, $g, $b] = self::toRgb($color);

        $max = max($r, $g, $b);
        $min = min($r, $g, $b);
        $l = ($max + $min) / 2;

        // A grey has no hue to preserve; every tint of it is a grey too, so
        // returning 0/0 is correct rather than a special case.
        if ($max === $min) {
            return [0.0, 0.0, $l];
        }

        $d = $max - $min;
        $s = $l > 0.5 ? $d / (2 - $max - $min) : $d / ($max + $min);

        $h = match ($max) {
            $r => fmod(($g - $b) / $d * 60.0, 360.0),
            $g => (($b - $r) / $d * 60.0) + 120.0,
            default => (($r - $g) / $d * 60.0) + 240.0,
        };

        return [$h < 0.0 ? $h + 360.0 : $h, $s, $l];
    }

    private static function hslToHex(float $h, float $s, float $l): string
    {
        $h = fmod($h, 360.0);
        if ($h < 0.0) {
            $h += 360.0;
        }

        $c = (1 - abs(2 * $l - 1)) * $s;
        $x = $c * (1 - abs(fmod($h / 60.0, 2.0) - 1));
        $m = $l - $c / 2;

        [$r, $g, $b] = match ((int) floor($h / 60.0) % 6) {
            0 => [$c, $x, 0.0],
            1 => [$x, $c, 0.0],
            2 => [0.0, $c, $x],
            3 => [0.0, $x, $c],
            4 => [$x, 0.0, $c],
            default => [$c, 0.0, $x],
        };

        return self::rgbToHex($r + $m, $g + $m, $b + $m);
    }

    /** @return array{float, float, float} channels in [0, 1] */
    private static function toRgb(string $color): array
    {
        $hex = strtolower(trim($color));
        if (!str_starts_with($hex, '#')) {
            $hex = '#' . $hex;
        }

        if (preg_match('/^#([0-9a-f]{6})$/', $hex, $m) !== 1) {
            throw new InvalidArgumentException(
                "Expected a #rrggbb colour, got \"$color\". The brand table is the source of "
                . 'truth for these values, so a malformed entry has to be a loud error here '
                . 'rather than a silently wrong swatch in the stylesheet.'
            );
        }

        return [
            hexdec(substr($m[1], 0, 2)) / 255,
            hexdec(substr($m[1], 2, 2)) / 255,
            hexdec(substr($m[1], 4, 2)) / 255,
        ];
    }

    private static function rgbToHex(float $r, float $g, float $b): string
    {
        return sprintf(
            '#%02x%02x%02x',
            (int) round(self::clamp($r, 0.0, 1.0) * 255),
            (int) round(self::clamp($g, 0.0, 1.0) * 255),
            (int) round(self::clamp($b, 0.0, 1.0) * 255),
        );
    }

    private static function lowerHex(string $color): string
    {
        return strtolower('#' . ltrim(trim($color), '#'));
    }

    private static function clamp(float $value, float $min, float $max): float
    {
        return max($min, min($max, $value));
    }
}
