<?php

declare(strict_types=1);

namespace App\Twig;

use App\Service\QrEncoder;
use Com\Tecnick\Barcode\Barcode;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

/**
 * Twig functions for QR codes and barcodes.
 *
 * Provides `qr_code`, `barcode` and `pdf417` filters/functions so templates —
 * especially the mPDF templates under resources/views/mpdf/ — can embed
 * scannable symbols without an external image API.
 *
 * QR codes are generated by the project's own {@see QrEncoder} (tested, no extra
 * dependency). 1-D barcodes and PDF417 use the `tecnickcom/tc-lib-barcode` library.
 */
final class BarcodeExtension extends AbstractExtension
{
    private Barcode $barcode;

    public function __construct()
    {
        $this->barcode = new Barcode();
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('qr_code', [$this, 'qrCode'], ['is_safe' => ['html']]),
            new TwigFunction('barcode', [$this, 'barcode'], ['is_safe' => ['html']]),
            new TwigFunction('pdf417', [$this, 'pdf417'], ['is_safe' => ['html']]),
        ];
    }

    /**
     * Render a QR code as inline SVG.
     *
     * Uses the project's QrEncoder — the same encoder behind the app-download QR
     * on /app — so there is a single, tested implementation for both web and PDF.
     *
     * @param string $data     The payload to encode.
     * @param int    $border   Quiet zone in modules (ISO minimum is 4).
     * @param int    $scale    Pixel size of each module.
     * @param string $fgColor  Foreground colour (SVG/CSS notation).
     * @param string $bgColor  Background colour; `#ffffff` for opaque on dark pages.
     */
    public function qrCode(
        string $data,
        int $border = 4,
        int $scale = 5,
        string $fgColor = '#000000',
        string $bgColor = '#ffffff',
    ): string {
        try {
            return QrEncoder::encode($data)->toSvg($border, $scale, $fgColor, $bgColor);
        } catch (\Throwable) {
            return '';
        }
    }

    /**
     * Render a 1-D / linear barcode as inline SVG.
     *
     * Wraps `tecnickcom/tc-lib-barcode`; accepts any type token it understands,
     * e.g. `C128`, `EAN13`, `I25`, `C39`.
     *
     * @param string $type   Barcode type token (see Barcode::BARCODETYPES).
     * @param string $code   The data to encode.
     * @param int    $width   Bar width in user units (negative = module multiplier).
     * @param int    $height  Bar height in user units (negative = module multiplier).
     * @param string $color   Foreground colour.
     */
    public function barcode(
        string $type,
        string $code,
        int $width = -1,
        int $height = -1,
        string $color = 'black',
    ): string {
        try {
            $obj = $this->barcode->getBarcodeObj($type, $code, $width, $height, $color);
            return $obj->getInlineSvgCode();
        } catch (\Throwable) {
            return '';
        }
    }

    /**
     * Render a PDF417 (2-D stacked) barcode as inline SVG.
     *
     * @param string $data   The payload to encode.
     * @param int    $width   Target width in user units.
     * @param int    $height  Target height in user units.
     * @param string $color   Foreground colour.
     */
    public function pdf417(
        string $data,
        int $width = 6,
        int $height = 3,
        string $color = 'black',
    ): string {
        try {
            $obj = $this->barcode->getBarcodeObj('PDF417', $data, $width, $height, $color);
            return $obj->getInlineSvgCode();
        } catch (\Throwable) {
            return '';
        }
    }
}
