<?php

/**
 * Bootstrap file for the standalone `vendor/bin/yii-db-migration` tool.
 *
 * The vendor binary (`vendor/yiisoft/db-migration/bin/yii-db-migration`) does `require $rootPath . '/yii-db-migration.php'`
 * and expects a plain array of options back. This project is based on the Yii3 application template, which wires
 * everything through `config/`, so this file builds the very same console container the `yii` entry point builds and
 * hands the migration tool the application database connection.
 *
 * Do NOT duplicate DB credentials here: they come from `App\Env` (`.env` in development, real env vars in production),
 * exactly as in `config/common/di/db.php`.
 */

declare(strict_types=1);

use App\Environment;
use Yiisoft\Db\Connection\ConnectionInterface;
use Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner;

// Same bootstrap as the `yii` entry point: Composer autoloader, `.env` and environment validation.
require_once __DIR__ . '/src/bootstrap.php';

/**
 * The DI container is what the migration tool injects into migration constructors, so a migration can type-hint
 * `ServiceRepository`, `LoggerInterface` and so on. Reusing the application runner keeps a single source of truth for
 * the `di-console` definitions instead of assembling a second, drifting container here.
 */
$container = (new ConsoleApplicationRunner(
    rootPath: __DIR__,
    debug: Environment::appDebug(),
    checkEvents: false,
    environment: Environment::appEnv(),
))->getContainer();

return [
    /**
     * Database connection. Comes from `config/common/di/db.php`, i.e. `DB_DSN` / `DB_USERNAME` / `DB_PASSWORD`.
     */
    'db' => $container->get(ConnectionInterface::class),

    /**
     * PSR-11 container used to resolve migration dependencies. Migrations in this project are plain classes in
     * `migrations/` without a namespace, so `sourcePaths` is the only thing that has to point at them.
     */
    'container' => $container,

    /**
     * Directory for `migrate:new` to write generated migrations into. Kept in sync with `config/console/params.php`.
     */
    'newMigrationPath' => __DIR__ . '/migrations',

    /**
     * Directories to scan for existing migrations.
     */
    'sourcePaths' => [__DIR__ . '/migrations'],

    /**
     * Migrations are not namespaced, so this stays empty.
     */
    'newMigrationNamespace' => '',
    'sourceNamespaces' => [],

    /**
     * Table holding the applied migration history.
     */
    'historyTable' => '{{%migration}}',

    /**
     * Maximum length of a generated migration name.
     */
    'migrationNameLimit' => 180,

    /**
     * Table names generated by `migrate:create` are prefixed with `{{%...}}` so they follow `tablePrefix`.
     */
    'useTablePrefix' => true,

    /**
     * Maximum length of an SQL statement printed to the console. `null` means no limit.
     */
    'maxSqlOutputLength' => null,
];
